# Generated by Django 3.2.8 on 2021-11-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('face_participants', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('yes_votes', models.IntegerField()),
                ('no_votes', models.IntegerField()),
                ('real_participants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('number_from', models.CharField(max_length=20)),
                ('number_to', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('in_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_voting.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=None, null=True)),
                ('yes_word', models.CharField(max_length=20)),
                ('no_word', models.CharField(max_length=20)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_voting.sms')),
                ('in_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_voting.poll')),
            ],
        ),
    ]
