# Generated by Django 3.2.8 on 2021-11-07 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0002_auto_20211107_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='checked_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_voting.sms'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='no_votes',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='real_participants',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='yes_votes',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
