# Generated by Django 3.2.8 on 2021-11-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0003_auto_20211107_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_open',
        ),
        migrations.AddField(
            model_name='poll',
            name='remote_participants',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RemoteParticipant',
        ),
    ]
