# Generated by Django 3.2.8 on 2021-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0004_auto_20211107_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='face_participants',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='no_votes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='real_participants',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='remote_participants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='yes_votes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
