# Generated by Django 3.2.8 on 2021-11-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0005_auto_20211107_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='face_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='remote_participant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
