# Generated by Django 3.2.8 on 2021-11-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0007_auto_20211107_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='absent_face_participants',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='absent_remote_participants',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='number_to',
        ),
        migrations.AddField(
            model_name='poll',
            name='doctor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='jury_add_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='jury_full_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='face_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='no_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='remote_participants',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='yes_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sms',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
