# Generated by Django 3.2.8 on 2021-11-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0008_auto_20211110_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
    ]
