# Generated by Django 3.2.8 on 2021-11-10 04:33

from django.db import migrations

def load_words(apps, schema_editor):
    Word = apps.get_model('sms_voting', 'Word')
    with open('sms_voting/migrations/wordlist') as f:
        Word.objects.bulk_create(Word(word=word.strip()) for word in f)

class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0009_word'),
    ]

    operations = [
            migrations.RunPython(load_words)
    ]
