# Generated by Django 3.2.8 on 2021-11-10 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0010_add_word_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='no_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_bulletin_no', to='sms_voting.word'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='yes_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_bulletin_yes', to='sms_voting.word'),
        ),
    ]
