# Generated by Django 3.2.8 on 2021-11-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_voting', '0011_auto_20211110_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='result',
        ),
        migrations.AlterField(
            model_name='poll',
            name='remote_participants',
            field=models.TextField(default=''),
        ),
    ]
